#!/usr/bin/env node
// decorate-graph.mjs — in-place Obsidian-native graph decoration for a CORE
// unit store. Replaces the export-only OKF/Obsidian projection
// (render-okf-export.mjs): instead of a separate `_okf-export/` copy that
// goes stale the moment it's generated, each real unit file in `_memories/`
// gets a marker-delimited, auto-regenerated `[[wikilink]]` block appended
// directly to its own body. Point Obsidian at the live store; there is only
// ever one copy.
//
// Design source: David's 2026-07-21 direction change (in-place decoration
// over export — see mailbox thread
// core-claude--in-place-graph-decoration-replaces-okf-export) plus
// Antigravity's same-day architectural review (three constraints, all
// applied below):
//   1. Dangling edges to archived/retired targets are stripped, not
//      rendered as Obsidian "ghost" nodes — a retired target is simply
//      absent from activeById, same filtering render-okf-export.mjs
//      already used for this.
//   2. The edges block is destructive and structurally isolated from the
//      human-authored unit body behind strict markers, with an in-block
//      warning comment.
//   3. Idempotent: a unit's file is only rewritten when its computed block
//      differs from what's already on disk.
//
// Anti-resurrection note: retired/archived units are relocated to
// `_memories/archive/` (enforced by check-units.mjs's `retired-in-active`/
// `archived-in-active` rules) and are OUT of loadSnapshot's active-unit
// population, so this script never decorates them and never links to them.
//
// CLI:
//   node decorate-graph.mjs <project-dir> [--check] [--dry-run]

import { readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadSnapshot } from './generate-summary-index.mjs';
import { atomicWriteFileSync } from './fs-atomic.mjs';
import { withFileLock } from './file-lock.mjs';

export const EDGES_BEGIN = '<!-- CORE:BEGIN_EDGES -->';
export const EDGES_END = '<!-- CORE:END_EDGES -->';
const EDGES_WARNING = '<!-- Auto-generated by CORE — do not edit inside this block. It is fully regenerated from the unit\'s edges: frontmatter on every run; anything written here will be overwritten. -->';
const EDGES_HEADING = '## Related';

/**
 * findExistingEdgesBlock — same marker-scan pattern as hot-section.mjs's
 * findExistingBlock, applied to a unit body instead of PROJECT.md. Inclusive
 * of the trailing newline(s) after the end marker so replacement is clean.
 */
export function findExistingEdgesBlock(text) {
  const beginIdx = text.indexOf(EDGES_BEGIN);
  const endIdx = text.indexOf(EDGES_END);
  if (beginIdx === -1 || endIdx === -1 || endIdx < beginIdx) return null;
  let blockEnd = endIdx + EDGES_END.length;
  while (blockEnd < text.length && text[blockEnd] === '\n') blockEnd++;
  return { start: beginIdx, end: blockEnd };
}

/**
 * wikiLink — a plain `[[id]]` resolves in Obsidian by filename (without the
 * .md extension), which is exactly the unit id since files are named
 * `<id>.md`. No display-alias piping: the id itself is already the
 * human-legible label CORE units use everywhere else (mailbox, indexes,
 * PROJECT.md), so a second, divergent label here would just be one more
 * thing that can drift.
 */
function wikiLink(id) {
  return `[[${id}]]`;
}

/**
 * renderEdgesBlock — deterministic edge order (type, then target — same
 * convention as render-okf-export.mjs), filtered to active-store targets
 * only. Returns '' when a unit has no kept edges (nothing to render, and
 * findExistingEdgesBlock below removes any stale block in that case).
 */
export function renderEdgesBlock(unitId, edges, activeById) {
  const kept = [];
  for (const e of [...(edges || [])].sort((a, b) =>
    a.type.localeCompare(b.type) || a.target.localeCompare(b.target))) {
    if (!activeById.has(e.target)) continue; // retired/archived/dangling/external
    kept.push(`- ${e.type}: ${wikiLink(e.target)}`);
  }
  if (kept.length === 0) return '';
  return `${EDGES_BEGIN}\n${EDGES_WARNING}\n${EDGES_HEADING}\n${kept.join('\n')}\n${EDGES_END}\n`;
}

/**
 * decorateUnitText — apply (or remove) the edges block in one unit's raw
 * text. Returns the original text unchanged if the computed block is
 * byte-identical to what's already there (idempotent — constraint 3).
 */
export function decorateUnitText(text, unitId, edges, activeById) {
  const block = renderEdgesBlock(unitId, edges, activeById);
  const existing = findExistingEdgesBlock(text);

  if (!block) {
    // No kept edges: remove a stale block if present, otherwise no-op.
    if (!existing) return text;
    return text.slice(0, existing.start) + text.slice(existing.end);
  }

  if (existing) {
    return text.slice(0, existing.start) + block + text.slice(existing.end);
  }
  // No existing block: append at the end of the file, separated by a blank line.
  const trimmed = text.replace(/\n+$/, '\n');
  return (trimmed.endsWith('\n') ? trimmed : trimmed + '\n') + '\n' + block;
}

/**
 * decorateStore — the store-wide pass. One atomic snapshot (same
 * loadSnapshot(..., {captureBodies:true, retainRaw:true}) render-okf-export
 * uses), so ids/edges/raw bytes all derive from the same read — no
 * TOCTOU window between deciding what to link and what bytes to patch.
 *
 * Only ever touches top-level active units (loadSnapshot's own population);
 * archive/ is out of scope by construction, matching iterActiveUnits.
 */
export function decorateStore(projectDir, { dryRun = false } = {}) {
  const cap = loadSnapshot(projectDir, { captureBodies: true, retainRaw: true });
  const units = cap.index.units;
  const activeById = new Map(units.map(u => [u.id, u]));
  const memoriesDir = join(resolve(projectDir), '_memories');

  const changed = [];
  const unchanged = [];
  for (const u of units) {
    const raw = cap.raw?.[u.path];
    if (raw === undefined) continue; // scaffolding/unreadable — nothing to decorate
    const text = raw.toString('utf8');
    const updated = decorateUnitText(text, u.id, cap.edges[u.id] || [], activeById);
    if (updated !== text) {
      changed.push(u.path);
      if (!dryRun) atomicWriteFileSync(join(memoriesDir, ...u.path.split('/')), updated);
    } else {
      unchanged.push(u.path);
    }
  }

  return {
    snapshot_id: cap.snapshotId,
    total_units: units.length,
    changed,
    unchanged_count: unchanged.length,
    dry_run: dryRun,
  };
}

/**
 * decorateStoreLocked — decorateStore serialized under the project's file
 * lock (same lock file-lock.mjs's other callers use), so a concurrent
 * hygiene pass and a manual decorate-graph run never interleave writes to
 * the same unit file.
 */
export function decorateStoreLocked(projectDir, opts = {}) {
  const lockPath = join(resolve(projectDir), '_memories', '.decorate-graph.lock');
  return withFileLock(lockPath, () => decorateStore(projectDir, opts), { retries: 3, retryDelayMs: 50 });
}

// ---------- CLI ----------

function main(argv) {
  const positionals = argv.filter(a => !a.startsWith('--'));
  const projectDir = resolve(positionals[0] || process.cwd());
  const check = argv.includes('--check');
  const dryRun = check || argv.includes('--dry-run');

  const result = decorateStoreLocked(projectDir, { dryRun });
  if (result.changed.length === 0) {
    process.stdout.write(`decorate-graph: ${result.total_units} units, none needed a change (snapshot ${result.snapshot_id.slice(0, 12)}).\n`);
    return 0;
  }

  const verb = dryRun ? 'would update' : 'updated';
  process.stdout.write(`decorate-graph: ${verb} ${result.changed.length}/${result.total_units} unit(s) (snapshot ${result.snapshot_id.slice(0, 12)}):\n`);
  for (const p of result.changed) process.stdout.write(`  ${p}\n`);

  if (check) return result.changed.length > 0 ? 1 : 0;
  return 0;
}

const _cliEntry = (() => { try { return fileURLToPath(import.meta.url) === resolve(process.argv[1]); } catch { return false; } })();
if (_cliEntry) {
  process.exit(main(process.argv.slice(2)));
}
