#!/usr/bin/env node
// decorate-graph.mjs — in-place Obsidian-native graph decoration for a CORE
// unit store. Each real unit file in `_memories/`
// gets a marker-delimited, auto-regenerated `[[wikilink]]` block appended
// directly to its own body — no separate export copy that goes stale the
// moment it's generated. Point Obsidian at the live store; there is only
// ever one copy.
//
// Three constraints, all applied below:
//   1. Dangling edges to archived/retired targets are stripped, not
//      rendered as Obsidian "ghost" nodes — a retired target is simply
//      absent from activeById.
//   2. The edges block is destructive and structurally isolated from the
//      human-authored unit body behind strict markers, with an in-block
//      warning comment.
//   3. Idempotent: a unit's file is only rewritten when its computed block
//      differs from what's already on disk.
//
// Anti-resurrection note: a top-level retired unit (status: retired) is kept
// in place and excluded by status filtering; an archived unit is physically
// relocated to `_memories/archive/` (check-units.mjs's `archived-in-active`
// rule flags one left behind) and excluded by path. Either way it's OUT of
// loadSnapshot's active-unit population, so this script never decorates it
// and never links to it.
//
// CLI:
//   node decorate-graph.mjs <project-dir> [--check] [--dry-run]

import { readFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadSnapshot } from './generate-summary-index.mjs';
import { atomicWriteFileSync } from './fs-atomic.mjs';
import { withFileLock } from './file-lock.mjs';
import { hashText, stampFiles, readProjectCache } from './state-cache.mjs';
import { writeGuardDecision } from './lifecycle-core.mjs';
import { EDGES_BEGIN, EDGES_END } from './unit-vocab.mjs';

export { EDGES_BEGIN, EDGES_END };
const EDGES_WARNING = '<!-- Auto-generated by CORE — do not edit inside this block. It is fully regenerated from the unit\'s edges: frontmatter on every run; anything written here will be overwritten. -->';
const EDGES_HEADING = '## Related';

function countOccurrences(text, needle) {
  let count = 0, idx = 0;
  while ((idx = text.indexOf(needle, idx)) !== -1) { count++; idx += needle.length; }
  return count;
}

/**
 * findExistingEdgesBlock — fail-closed marker scan
 * (a naive first-begin/first-end indexOf pairing would corrupt a file
 * that already has a malformed marker state — e.g. one orphaned BEGIN with
 * no END, then a human-authored line, then a later run's own generated END
 * lands past it and everything in between gets silently deleted).
 *
 * Returns { ok: true, block: null }        — no markers at all, clean slate.
 * Returns { ok: true, block: {start,end} } — exactly one correctly-ordered
 *                                            BEGIN/END pair, safe to replace.
 * Returns { ok: false, block: null }       — any other shape (duplicate
 *                                            markers, an orphaned marker,
 *                                            END before BEGIN) — refuse to
 *                                            touch this file rather than guess.
 */
export function findExistingEdgesBlock(text) {
  const beginCount = countOccurrences(text, EDGES_BEGIN);
  const endCount = countOccurrences(text, EDGES_END);
  if (beginCount === 0 && endCount === 0) return { ok: true, block: null };
  if (beginCount !== 1 || endCount !== 1) return { ok: false, block: null };
  const beginIdx = text.indexOf(EDGES_BEGIN);
  const endIdx = text.indexOf(EDGES_END);
  if (endIdx < beginIdx) return { ok: false, block: null };
  let blockEnd = endIdx + EDGES_END.length;
  while (blockEnd < text.length && text[blockEnd] === '\n') blockEnd++;
  return { ok: true, block: { start: beginIdx, end: blockEnd } };
}

/**
 * wikiLink — a plain `[[id]]` resolves in Obsidian by filename (without the
 * .md extension), which is exactly the unit id since files are named
 * `<id>.md`. No display-alias piping: the id itself is already the
 * human-legible label CORE units use everywhere else (mailbox, indexes,
 * PROJECT.md), so a second, divergent label here would just be one more
 * thing that can drift.
 */
function wikiLink(id) {
  return `[[${id}]]`;
}

/**
 * renderEdgesBlock — deterministic edge order (type, then target — same
 * convention as render-okf-export.mjs), filtered to active-store targets
 * only. Returns '' when a unit has no kept edges (nothing to render, and
 * findExistingEdgesBlock below removes any stale block in that case).
 */
export function renderEdgesBlock(unitId, edges, activeById) {
  const kept = [];
  for (const e of [...(edges || [])].sort((a, b) =>
    a.type.localeCompare(b.type) || a.target.localeCompare(b.target))) {
    if (!activeById.has(e.target)) continue; // retired/archived/dangling/external
    kept.push(`- ${e.type}: ${wikiLink(e.target)}`);
  }
  if (kept.length === 0) return '';
  return `${EDGES_BEGIN}\n${EDGES_WARNING}\n${EDGES_HEADING}\n${kept.join('\n')}\n${EDGES_END}\n`;
}

/**
 * decorateUnitText — apply (or remove) the edges block in one unit's raw
 * text. Returns the original text unchanged if the computed block is
 * byte-identical to what's already there (idempotent — constraint 3).
 *
 * Throws MALFORMED_EDGES_MARKERS if the file's marker state isn't either
 * "no markers" or "exactly one correctly-ordered pair" — the caller
 * (decorateStore) catches this per-file and refuses only that file, so one
 * corrupted unit never blocks or corrupts its siblings.
 */
export function decorateUnitText(text, unitId, edges, activeById) {
  const scan = findExistingEdgesBlock(text);
  if (!scan.ok) {
    throw Object.assign(
      new Error(`malformed CORE:BEGIN_EDGES/END_EDGES marker state in ${unitId} — refusing to touch this file`),
      { code: 'MALFORMED_EDGES_MARKERS' },
    );
  }
  const block = renderEdgesBlock(unitId, edges, activeById);
  const existing = scan.block;

  if (!block) {
    // No kept edges: remove a stale block if present, otherwise no-op.
    if (!existing) return text;
    return text.slice(0, existing.start) + text.slice(existing.end);
  }

  if (existing) {
    return text.slice(0, existing.start) + block + text.slice(existing.end);
  }
  // No existing block: append at the end of the file, separated by a blank line.
  const trimmed = text.replace(/\n+$/, '\n');
  return (trimmed.endsWith('\n') ? trimmed : trimmed + '\n') + '\n' + block;
}

/**
 * hashOutsideEdgesBlock — content hash of a unit's text with the
 * marker-delimited edges block excluded, so a later mismatch against the
 * cached stamp can tell "decorate-graph regenerated its own block" from "a
 * human edited this unit" — same construction as hot-section.mjs's
 * hashOutsideHotBlock for PROJECT.md's hot section. decorate-graph never
 * touches anything outside EDGES_BEGIN/EDGES_END by construction (see
 * decorateUnitText), so if this hash still matches the cached one, nothing
 * outside the edges block changed regardless of what last_written_by claims.
 *
 * A malformed marker state (findExistingEdgesBlock returns {ok:false}) hashes
 * the WHOLE text as "outside" — decorateStore refuses to touch (and never
 * stamps) a malformed file anyway, so this path only matters for a stamp
 * that predates a marker corruption introduced by something other than this
 * script, which correctly falls through to "outside changed" on comparison.
 */
export function hashOutsideEdgesBlock(text) {
  const t = String(text || '');
  const scan = findExistingEdgesBlock(t);
  const block = scan.ok ? scan.block : null;
  const outside = block ? t.slice(0, block.start) + t.slice(block.end) : t;
  return hashText(outside);
}

/**
 * classifyUnitChange — deterministic classifier for a unit-file hash
 * mismatch against the cached stamp, mirroring hot-section.mjs's
 * classifyProjectMdChange for PROJECT.md's hot block. Returns:
 *   'no-baseline'        — no cached outside_hash to compare against (older
 *                          cache entry predating this fix, or never stamped).
 *   'edges-block-only'   — everything outside the edges block is
 *                          byte-identical to the last recorded write; safe to
 *                          treat as CORE's own decoration regardless of the
 *                          whole-file hash mismatch.
 *   'outside-changed'    — content outside the edges block changed since the
 *                          last stamp. decorate-graph.mjs cannot have
 *                          produced this; MUST be treated as a genuine user
 *                          edit.
 */
export function classifyUnitChange(cachedStamp, currentText) {
  if (!cachedStamp || typeof cachedStamp.outside_hash !== 'string') return 'no-baseline';
  return hashOutsideEdgesBlock(currentText) === cachedStamp.outside_hash ? 'edges-block-only' : 'outside-changed';
}

/**
 * decorateStore — the store-wide pass. One atomic snapshot (same
 * loadSnapshot(..., {captureBodies:true, retainRaw:true}) render-okf-export
 * uses), so ids/edges/raw bytes all derive from the same read — no
 * TOCTOU window between deciding what to link and what bytes to patch.
 *
 * Only ever touches top-level active units (loadSnapshot's own population);
 * archive/ is out of scope by construction, matching iterActiveUnits.
 */
export function decorateStore(projectDir, { dryRun = false, now, home } = {}) {
  const cap = loadSnapshot(projectDir, { captureBodies: true, retainRaw: true });
  const units = cap.index.units;
  const activeById = new Map(units.map(u => [u.id, u]));
  const memoriesDir = join(resolve(projectDir), '_memories');

  // Authorship boundary: read the state cache ONCE, before
  // any of this run's writes land, as the pre-write baseline every unit gets
  // classified against below. Stamping a fresh
  // outside_hash without that check would launder a human-authored region
  // that had ALREADY diverged
  // from the last known-good baseline (a between-session user edit nobody
  // has reconciled yet), making the divergence permanently
  // undetectable: the user's bytes survive, but the fact that they changed
  // is never observed, attributed, or propagated. See
  // classifyUnitChange below for what "already diverged" means.
  const preWriteCache = readProjectCache(projectDir);

  const changed = [];
  const unchanged = [];
  const refused = [];
  const needsReconciliation = [];
  const stampEntries = [];
  for (const u of units) {
    const raw = cap.raw?.[u.path];
    if (raw === undefined) continue; // scaffolding/unreadable — nothing to decorate
    const text = raw.toString('utf8');

    let updated;
    try {
      updated = decorateUnitText(text, u.id, cap.edges[u.id] || [], activeById);
    } catch (e) {
      if (e.code === 'MALFORMED_EDGES_MARKERS') { refused.push({ path: u.path, reason: e.message }); continue; }
      throw e;
    }

    if (updated === text) { unchanged.push(u.path); continue; }

    const filePath = join(memoriesDir, ...u.path.split('/'));

    // Refuse to decorate (and never re-stamp) a file whose human-authored
    // region already disagrees with the last established baseline. Gated on
    // `cachedStamp` being present: a file with NO prior cache entry has no
    // established baseline to violate — its first-ever decoration is safe
    // and is exactly how that baseline gets established in the first place.
    // A file that DOES have a prior entry but classifies as 'outside-changed'
    // (a real edit since the last stamp) or 'no-baseline' (a pre-fix entry
    // recorded before outside_hash existed, so we can't prove what "outside"
    // looked like) is an unreconciled user edit already in flight — decorate
    // must not touch it or launder it into a fresh stamp.
    const cachedStamp = preWriteCache.files[filePath];
    const classification = classifyUnitChange(cachedStamp, text);
    // Shared refuse-or-proceed rule (lifecycle-core.mjs) — identical logic to
    // hot-section and compact-project. A stamped file refuses on
    // 'outside-changed'/'no-baseline'; a file with NO stamp at all ALWAYS
    // refuses (session timing cannot prove
    // authorship). A legitimately new unit is decoratable because its creating
    // writer stamped it at creation (lifecycle-detect.mjs stampCreatedBaseline);
    // an un-stamped no-baseline unit is held and surfaced, never rewritten.
    const decision = writeGuardDecision({ cachedStamp, classification });
    if (!decision.proceed) {
      needsReconciliation.push({ path: u.path, classification: decision.classification });
      continue;
    }

    if (!dryRun) {
      // Stale-byte refusal: the file lock this
      // script runs under is private to decorate-graph, so it doesn't
      // serialize against a hygiene pass or a hand edit landing between the
      // snapshot read and this write. Re-read right before writing and
      // refuse if the bytes moved — a stale write here would silently
      // discard whatever the other writer just wrote.
      let current;
      try { current = readFileSync(filePath); } catch { current = null; }
      if (current === null || !current.equals(raw)) {
        refused.push({ path: u.path, reason: 'file changed on disk since the snapshot was captured — refusing a stale write' });
        continue;
      }
      atomicWriteFileSync(filePath, updated);
      // Stamp the state cache in the same operation, so next session's
      // edit-detection recognizes this as CORE's own write rather than a
      // between-session user edit (in code, never left to the agent by
      // prose instruction — same mechanism as hot-section.mjs).
      stampEntries.push({
        path: filePath,
        hash: hashText(updated),
        lastWrittenBy: 'decorate-graph',
        extra: { outside_hash: hashOutsideEdgesBlock(updated) },
      });
    }
    changed.push(u.path);
  }

  // Truthful stamp-failure surfacing: the unit files landed
  // on disk; if their authorship stamp didn't, report attribution-unknown so
  // the caller surfaces it, rather than reporting a clean decoration.
  let stampOutcome = { stamped: true };
  if (!dryRun && stampEntries.length > 0) stampOutcome = stampFiles(projectDir, stampEntries, { now, home });

  return {
    snapshot_id: cap.snapshotId,
    total_units: units.length,
    changed,
    unchanged_count: unchanged.length,
    refused,
    needs_reconciliation: needsReconciliation,
    attribution: stampOutcome && stampOutcome.stamped === false ? stampOutcome : { stamped: true },
    dry_run: dryRun,
  };
}

/**
 * decorateStoreLocked — decorateStore serialized under the project's file
 * lock (same lock file-lock.mjs's other callers use), so a concurrent
 * hygiene pass and a manual decorate-graph run never interleave writes to
 * the same unit file.
 */
export function decorateStoreLocked(projectDir, opts = {}) {
  const lockPath = join(resolve(projectDir), '_memories', '.decorate-graph.lock');
  return withFileLock(lockPath, () => decorateStore(projectDir, opts), { retries: 3, retryDelayMs: 50 });
}

// ---------- CLI ----------

function main(argv) {
  const positionals = argv.filter(a => !a.startsWith('--'));
  const projectDir = resolve(positionals[0] || process.cwd());
  const check = argv.includes('--check');
  const dryRun = check || argv.includes('--dry-run');

  const result = decorateStoreLocked(projectDir, { dryRun });

  if (result.changed.length === 0 && result.refused.length === 0 && result.needs_reconciliation.length === 0) {
    process.stdout.write(`decorate-graph: ${result.total_units} units, none needed a change (snapshot ${result.snapshot_id.slice(0, 12)}).\n`);
    return 0;
  }

  if (result.changed.length > 0) {
    const verb = dryRun ? 'would update' : 'updated';
    process.stdout.write(`decorate-graph: ${verb} ${result.changed.length}/${result.total_units} unit(s) (snapshot ${result.snapshot_id.slice(0, 12)}):\n`);
    for (const p of result.changed) process.stdout.write(`  ${p}\n`);
  }

  // Every refusal is a real, user-actionable problem (a malformed marker
  // state, or a stale-byte race) -- printing "none needed a change" while
  // silently swallowing these would be a genuine reporting gap.
  // Always print them, and let a refusal alone still exit nonzero
  // even outside --check, since it means a file was NOT decorated as asked.
  if (result.refused.length > 0) {
    process.stderr.write(`decorate-graph: ${result.refused.length} file(s) refused, need a manual look:\n`);
    for (const r of result.refused) process.stderr.write(`  ${r.path}: ${r.reason}\n`);
  }

  // A unit whose human-authored region already diverged from the last known
  // baseline is a real,
  // user-visible signal — not a silent skip. Printing it alongside refusals
  // and treating it as exit-nonzero keeps the same "never claim quiet
  // success while something needs a look" discipline as the refused-file path.
  if (result.needs_reconciliation.length > 0) {
    process.stderr.write(`decorate-graph: ${result.needs_reconciliation.length} file(s) need reconciliation before decoration (unreconciled user edit outside the generated block):\n`);
    for (const r of result.needs_reconciliation) process.stderr.write(`  ${r.path}: ${r.classification}\n`);
  }

  // Attribution failure: files wrote but a baseline stamp
  // didn't land. Never report clean success over an unknown-authorship state.
  const attributionFailed = result.attribution && result.attribution.stamped === false;
  if (attributionFailed) {
    process.stderr.write(
      `decorate-graph: WROTE unit files but the authorship stamp failed ` +
      `(${result.attribution.outcome}: ${result.attribution.reason}) — attribution unknown, ` +
      `recovery-required before the next lifecycle pass trusts these files.\n`
    );
  }

  if (check) return (result.changed.length > 0 || result.refused.length > 0 || result.needs_reconciliation.length > 0 || attributionFailed) ? 1 : 0;
  return (result.refused.length > 0 || result.needs_reconciliation.length > 0 || attributionFailed) ? 1 : 0;
}

const _cliEntry = (() => { try { return fileURLToPath(import.meta.url) === resolve(process.argv[1]); } catch { return false; } })();
if (_cliEntry) {
  process.exit(main(process.argv.slice(2)));
}
