import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import {
  checkIntegrity, iterActiveUnits, iterAllUnitFiles,
} from '../../skills/core/scripts/check-units.mjs';

function withStore(fn) {
  const root = mkdtempSync(join(tmpdir(), 'check-units-'));
  try {
    const memories = join(root, '_memories');
    mkdirSync(memories, { recursive: true });
    return fn(memories);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
}

function unit({
  id,
  body = '',
  type = 'decision',
  edges = '',
}) {
  return [
    '---',
    `id: ${id}`,
    `type: ${type}`,
    'status: active',
    'created: 2026-05-30',
    'updated: 2026-05-30',
    'topics:',
    '  - tests',
    edges,
    '---',
    '',
    body || `# ${id}`,
    '',
  ].filter(line => line !== '').join('\n');
}

test('iterActiveUnits: validates real units that merely mention the render-only marker', () => withStore((memories) => {
  writeFileSync(join(memories, 'real-unit.md'), unit({
    id: 'real-unit',
    body: '# Real unit\n\nThis unit discusses the phrase Render-only artifact as prose.',
  }));

  const units = iterActiveUnits(memories);

  assert.equal(units.length, 1);
  assert.equal(units[0].id, 'real-unit');
}));

test('iterAllUnitFiles: keeps real unit files that merely mention the render-only marker', () => withStore((memories) => {
  writeFileSync(join(memories, 'real-unit.md'), unit({
    id: 'real-unit',
    body: '# Real unit\n\nThis unit discusses the phrase Render-only artifact as prose.',
  }));

  const stems = iterAllUnitFiles(memories).map(path => path.split('/').at(-1));

  assert.deepEqual(stems, ['real-unit.md']);
}));

test('iterActiveUnits and iterAllUnitFiles: skip generated capability drift log', () => withStore((memories) => {
  writeFileSync(join(memories, 'capability-drift-log.md'), [
    '# Capability Drift Log',
    '',
    '> Render-only artifact (not a unit). Regenerated by analyze-capability-drift.mjs. Generated 2026-05-30T00:00:00.000Z.',
    '',
  ].join('\n'));

  assert.deepEqual(iterActiveUnits(memories), []);
  assert.deepEqual(iterAllUnitFiles(memories), []);
}));

test('checkIntegrity: edge targets are not hidden by incidental render-only marker prose', () => withStore((memories) => {
  writeFileSync(join(memories, 'source.md'), unit({
    id: 'source',
    edges: [
      'edges:',
      '  - type: depends-on',
      '    target: target',
    ].join('\n'),
  }));
  writeFileSync(join(memories, 'target.md'), unit({
    id: 'target',
    body: '# Target\n\nMentions Render-only artifact while remaining a real unit.',
  }));

  const report = [];
  checkIntegrity(iterActiveUnits(memories), memories, new Date(Date.UTC(2026, 4, 30)), report);

  assert.equal(report.some(r => r.check === 'dangling-edge'), false);
}));
