import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import {
  checkIntegrity, checkSchema, exitCode, iterActiveUnits, iterAllUnitFiles,
  isExternalRef, BENIGN_WARN_CHECKS, VALID_EDGE_TYPES, EDGE_TYPE_NORMALIZE,
  resolveChecks,
} from '../../plugins/core/skills/core/scripts/check-units.mjs';

function withStore(fn) {
  const root = mkdtempSync(join(tmpdir(), 'check-units-'));
  try {
    const memories = join(root, '_memories');
    mkdirSync(memories, { recursive: true });
    return fn(memories);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
}

function unit({
  id,
  body = '',
  type = 'decision',
  edges = '',
}) {
  return [
    '---',
    `id: ${id}`,
    `type: ${type}`,
    'status: active',
    'created: 2026-05-30',
    'updated: 2026-05-30',
    'topics:',
    '  - tests',
    edges,
    '---',
    '',
    body || `# ${id}`,
    '',
  ].filter(line => line !== '').join('\n');
}

test('H3: --schema and --integrity together run BOTH checks (additive, not last-wins)', () => {
  // The old parser set mode= on each flag, so `--schema --integrity` silently
  // resolved to integrity-only and the schema check never fired — exactly what
  // /finalize was unknowingly doing. Flags are additive now.
  const both = resolveChecks(['--store', 'x', '--schema', '--integrity']);
  assert.equal(both.schema, true, 'schema check requested');
  assert.equal(both.integrity, true, 'integrity check requested');
  assert.equal(both.mode, 'all', 'label resolves to all');
});

test('H3: single flags and --mode still resolve as before (back-compat)', () => {
  assert.deepEqual(resolveChecks(['--schema']), { schema: true, integrity: false, mode: 'schema' });
  assert.deepEqual(resolveChecks(['--integrity']), { schema: false, integrity: true, mode: 'integrity' });
  assert.deepEqual(resolveChecks(['--mode', 'schema']), { schema: true, integrity: false, mode: 'schema' });
  assert.deepEqual(resolveChecks(['--mode', 'all']), { schema: true, integrity: true, mode: 'all' });
  // no mode flags at all -> both (the documented default)
  assert.deepEqual(resolveChecks(['--store', 'x']), { schema: true, integrity: true, mode: 'all' });
});

test('iterActiveUnits: returns real units regardless of their prose content', () => withStore((memories) => {
  writeFileSync(join(memories, 'real-unit.md'), unit({
    id: 'real-unit',
    body: '# Real unit\n\nOrdinary prose body — nothing here exempts it from validation.',
  }));

  const units = iterActiveUnits(memories);

  assert.equal(units.length, 1);
  assert.equal(units[0].id, 'real-unit');
}));

test('iterAllUnitFiles: returns real unit files regardless of their prose content', () => withStore((memories) => {
  writeFileSync(join(memories, 'real-unit.md'), unit({
    id: 'real-unit',
    body: '# Real unit\n\nOrdinary prose body — nothing here exempts it from validation.',
  }));

  const stems = iterAllUnitFiles(memories).map(path => path.split('/').at(-1));

  assert.deepEqual(stems, ['real-unit.md']);
}));

test('iterActiveUnits and iterAllUnitFiles: skip underscore-prefixed generated artifacts', () => withStore((memories) => {
  // Generated render artifacts use the `_` prefix; the prefix skip exempts them.
  writeFileSync(join(memories, '_capability-drift-log.md'), [
    '# Capability Drift Log',
    '',
    '> Generated artifact (not a unit). Regenerated by analyze-capability-drift.mjs.',
    '',
  ].join('\n'));

  assert.deepEqual(iterActiveUnits(memories), []);
  assert.deepEqual(iterAllUnitFiles(memories), []);
}));

test('checkIntegrity: edge targets resolve for ordinary real units', () => withStore((memories) => {
  writeFileSync(join(memories, 'source.md'), unit({
    id: 'source',
    edges: [
      'edges:',
      '  - type: depends-on',
      '    target: target',
    ].join('\n'),
  }));
  writeFileSync(join(memories, 'target.md'), unit({
    id: 'target',
    body: '# Target\n\nAn ordinary real unit.',
  }));

  const report = [];
  checkIntegrity(iterActiveUnits(memories), memories, new Date(Date.UTC(2026, 4, 30)), report);

  assert.equal(report.some(r => r.check === 'dangling-edge'), false);
}));

// --- Track A: validator fixes (Codex co-existence workstream, 2026-06-01) ---

test('A1: flow-style YAML topics array does NOT trigger topics-format warning', () => withStore((memories) => {
  // Inline array form — valid YAML, was being parsed as a scalar string.
  writeFileSync(join(memories, 'flow.md'), [
    '---', 'id: flow', 'type: decision', 'status: active',
    'created: 2026-05-30', 'updated: 2026-05-30',
    'topics: [source-authority, launch-readiness, execution]',
    '---', '', '# flow', '',
  ].join('\n'));

  const report = [];
  checkSchema(iterActiveUnits(memories), memories, report);

  const topicsWarn = report.filter(f => f.check === 'topics-format');
  assert.equal(topicsWarn.length, 0, 'flow-style array must parse as a list');
}));

test('A2: references-topic edge to vocabulary is NOT a dangling-edge', () => withStore((memories) => {
  writeFileSync(join(memories, 'has-topic-edge.md'), unit({
    id: 'has-topic-edge',
    edges: 'edges:\n  - {type: references-topic, target: memory-boundary}\n  - {type: cites, target: real-target}',
  }));
  writeFileSync(join(memories, 'real-target.md'), unit({ id: 'real-target' }));

  const report = [];
  checkIntegrity(iterActiveUnits(memories), memories, new Date('2026-05-30'), report);

  const danglers = report.filter(f => f.check === 'dangling-edge');
  assert.ok(!danglers.some(f => f.detail.includes('memory-boundary')),
    'references-topic target is controlled vocab, not a unit — must not dangle');
}));

// --- Cross-store / external-ref recognition (2026-06-03; obs-validator-cross-store-blindness) ---

test('cross-store prefixed edge target is external-ref, not dangling-edge', () => withStore((memories) => {
  writeFileSync(join(memories, 'src.md'), unit({
    id: 'src',
    edges: 'edges:\n  - {type: cites, target: feedback_no_naked_dc_references}',
  }));

  const report = [];
  checkIntegrity(iterActiveUnits(memories), memories, new Date('2026-06-03'), report);

  assert.equal(report.some(f => f.check === 'external-ref'), true,
    'feedback_-prefixed target lives in cross-project memory — recognized external, not a break');
  assert.equal(report.some(f => f.check === 'dangling-edge'), false);
}));

test('citation- and path-shaped edge targets are external-ref, not dangling-edge', () => withStore((memories) => {
  writeFileSync(join(memories, 'src.md'), unit({
    id: 'src',
    edges: [
      'edges:',
      '  - {type: cites, target: Park et al. 2023 (arxiv.org/abs/2304.03442)}',
      '  - {type: cites, target: docs/specs/2026-05-20-render-design.md}',
    ].join('\n'),
  }));

  const report = [];
  checkIntegrity(iterActiveUnits(memories), memories, new Date('2026-06-03'), report);

  assert.equal(report.filter(f => f.check === 'external-ref').length, 2,
    'a citation (whitespace/parens) and a file path (slash) are not unit ids');
  assert.equal(report.some(f => f.check === 'dangling-edge'), false);
}));

test('isExternalRef discriminates external refs from genuine unit ids', () => {
  assert.equal(isExternalRef('feedback_state_is_current_truth'), true);
  assert.equal(isExternalRef('project_bblens_tmobile_wrapper'), true);
  assert.equal(isExternalRef('reference_keel_handoff_channels'), true);
  assert.equal(isExternalRef('MemoryBank (arxiv.org/abs/2305.10250)'), true);
  assert.equal(isExternalRef('core-skill/skills/core/scripts/README.md'), true);
  // genuine unit-id shapes must NOT be masked — these still dangle if missing
  assert.equal(isExternalRef('dc-99-missing'), false);
  assert.equal(isExternalRef('obs-some-observation-2026-06-03'), false);
  assert.equal(isExternalRef('risk-12-mcp-write-arbitration'), false);
});

test('external-ref is a benign warn check (does not block exit code)', () => {
  assert.equal(BENIGN_WARN_CHECKS.has('external-ref'), true);
  assert.equal(exitCode([{ level: 'WARN', check: 'external-ref' }]), 0,
    'cross-store references must not degrade the exit code');
});

test('a genuinely missing unit-shaped target still flags dangling-edge (regression guard)', () => withStore((memories) => {
  writeFileSync(join(memories, 'src.md'), unit({
    id: 'src',
    edges: 'edges:\n  - {type: cites, target: dc-99-missing}',
  }));

  const report = [];
  checkIntegrity(iterActiveUnits(memories), memories, new Date('2026-06-03'), report);

  assert.equal(report.some(f => f.check === 'dangling-edge'), true,
    'a missing kebab-case unit id is a real break, not external');
}));

// --- Edge-type vocabulary: bless refines/amends, normalize relates (2026-06-03) ---

test('refines and amends are committed edge types (no edge-unknown-type)', () => withStore((memories) => {
  writeFileSync(join(memories, 'a.md'), unit({ id: 'a' }));
  writeFileSync(join(memories, 'b.md'), unit({ id: 'b' }));
  writeFileSync(join(memories, 'src.md'), unit({
    id: 'src',
    edges: 'edges:\n  - {type: refines, target: a}\n  - {type: amends, target: b}',
  }));

  const report = [];
  checkSchema(iterActiveUnits(memories), memories, report);

  assert.equal(report.some(f => f.check === 'edge-unknown-type'), false,
    'refines + amends are blessed — distinct from supersedes');
  assert.equal(VALID_EDGE_TYPES.has('refines'), true);
  assert.equal(VALID_EDGE_TYPES.has('amends'), true);
}));

test('relates flags edge-unknown-type and names its normalize target', () => withStore((memories) => {
  writeFileSync(join(memories, 'a.md'), unit({ id: 'a' }));
  writeFileSync(join(memories, 'src.md'), unit({
    id: 'src',
    edges: 'edges:\n  - {type: relates, target: a}',
  }));

  const report = [];
  checkSchema(iterActiveUnits(memories), memories, report);

  const warn = report.find(f => f.check === 'edge-unknown-type');
  assert.ok(warn, 'relates is not committed — must flag');
  assert.match(warn.detail, /normalize to 'cites'/, 'the safe-fix target is named for a mechanical relabel');
  assert.equal(EDGE_TYPE_NORMALIZE['relates'], 'cites');
}));

test('A3: exit-code tiers — benign warnings pass (0), degraded warn (1), fail (2)', () => {
  // Orphan/stale only → pass-with-warnings → 0 (must not block startup).
  assert.equal(exitCode([
    { level: 'WARN', check: 'orphan' },
    { level: 'WARN', check: 'stale' },
  ]), 0);
  // A non-benign warning is degraded → 1.
  assert.equal(exitCode([{ level: 'WARN', check: 'dangling-edge' }]), 1);
  // Any hard failure → 2.
  assert.equal(exitCode([
    { level: 'FAIL', check: 'required-field' },
    { level: 'WARN', check: 'orphan' },
  ]), 2);
  // Clean → 0.
  assert.equal(exitCode([]), 0);
});

test('SYN-005: unknown confidence-level and stability-class values WARN', () => withStore((memories) => {
  writeFileSync(join(memories, 'annotated.md'), [
    '---', 'id: annotated', 'type: observation', 'status: active',
    'created: 2026-05-30', 'updated: 2026-05-30', 'topics: [tests]',
    'confidence-level: banana',
    'stability-class: garbage',
    '---', '', '# annotated', '',
  ].join('\n'));

  const report = [];
  checkSchema(iterActiveUnits(memories), memories, report);

  assert.ok(report.some(f => f.check === 'confidence-level-value'), 'banana must WARN');
  assert.ok(report.some(f => f.check === 'stability-class-value'), 'garbage must WARN');
}));

test('SYN-005: schema confidence-level and stability-class values pass clean', () => withStore((memories) => {
  writeFileSync(join(memories, 'clean.md'), [
    '---', 'id: clean', 'type: observation', 'status: active',
    'created: 2026-05-30', 'updated: 2026-05-30', 'topics: [tests]',
    'confidence-level: sourced',
    'proposed-stability-class: durably-correct',
    '---', '', '# clean', '',
  ].join('\n'));

  const report = [];
  checkSchema(iterActiveUnits(memories), memories, report);

  assert.equal(report.some(f => f.check === 'confidence-level-value'), false);
  assert.equal(report.some(f => f.check === 'stability-class-value'), false);
}));

test('SYN-005 follow-up: legacy annotation WARNs are benign-class — store exits 0, not degraded', () => withStore((memories) => {
  // Pre-framework annotations like confidence-level: high / stability-class: stable
  // get WARN-level visibility but must NOT degrade an otherwise-healthy store.
  writeFileSync(join(memories, 'legacy.md'), [
    '---', 'id: legacy', 'type: observation', 'status: active',
    'created: 2026-05-30', 'updated: 2026-05-30', 'topics: [tests]',
    'confidence-level: high',
    'stability-class: stable',
    '---', '', '# legacy', '',
  ].join('\n'));

  const report = [];
  checkSchema(iterActiveUnits(memories), memories, report);

  assert.ok(report.some(f => f.level === 'WARN' && f.check === 'confidence-level-value'), 'legacy value still WARNs (visibility)');
  assert.ok(report.some(f => f.level === 'WARN' && f.check === 'stability-class-value'), 'legacy value still WARNs (visibility)');
  assert.equal(BENIGN_WARN_CHECKS.has('confidence-level-value'), true);
  assert.equal(BENIGN_WARN_CHECKS.has('stability-class-value'), true);
  assert.equal(exitCode(report), 0, 'legacy annotations alone must not degrade the store');
}));

test('SYN-007: observation-subdir units are audited only with includeObservations', () => withStore((memories) => {
  const obsDir = join(memories, 'observations', '2026-05');
  mkdirSync(obsDir, { recursive: true });
  writeFileSync(join(obsDir, 'obs-thing-2026-05-20.md'), [
    '---', 'id: obs-thing-2026-05-20', 'type: observation', 'status: bogus-status',
    'created: 2026-05-20', 'updated: 2026-05-20', 'topics: [tests]',
    '---', '', '# obs', '',
  ].join('\n'));

  const defaultReport = [];
  checkSchema(iterActiveUnits(memories), memories, defaultReport);
  assert.equal(defaultReport.some(f => f.unit_id === 'obs-thing-2026-05-20'), false,
    'default stays top-level-only');

  const fullReport = [];
  checkSchema(iterActiveUnits(memories, { includeObservations: true }), memories, fullReport);
  assert.ok(fullReport.some(f => f.unit_id === 'obs-thing-2026-05-20' && f.check === 'status-value'),
    'the full-store audit reaches the observation and flags its bogus status');
}));

// ---------- D7 / MEM-018: sources-missing provenance advisory ----------

test('MEM-018: an aged active non-observation unit with no sources WARNs sources-missing (benign)', () => withStore((memories) => {
  writeFileSync(join(memories, 'aged.md'), [
    '---', 'id: aged', 'type: decision', 'status: active',
    'created: 2026-01-01', 'updated: 2026-01-01', 'topics: [tests]',
    '---', '', '# aged', '',
  ].join('\n'));

  const report = [];
  checkIntegrity(iterActiveUnits(memories), memories, new Date(Date.UTC(2026, 5, 9)), report);

  assert.ok(report.some(f => f.check === 'sources-missing'), 'unknown provenance surfaced');
  assert.ok(BENIGN_WARN_CHECKS.has('sources-missing'), 'advisory — must not gate startup');
}));

test('MEM-018: fresh units and observations are exempt from sources-missing', () => withStore((memories) => {
  writeFileSync(join(memories, 'fresh.md'), unit({ id: 'fresh' })); // created 2026-05-30, today below makes it 10d old
  writeFileSync(join(memories, 'obs-young.md'), unit({ id: 'obs-young', type: 'observation' }));

  const report = [];
  checkIntegrity(iterActiveUnits(memories), memories, new Date(Date.UTC(2026, 5, 9)), report);

  assert.equal(report.some(f => f.check === 'sources-missing'), false);
}));

// ---------- D8 / MEM-008 + MEM-014: empty required fields FAIL, oversize WARNs ----------

test('MEM-008: a present-but-empty required field FAILs (type: with blank value)', () => withStore((memories) => {
  // `type: ` parses to an empty list (the parser treats a blank value as a
  // list opener), which passed both the key-presence check and the truthiness-
  // guarded value check.
  writeFileSync(join(memories, 'blank-type.md'), [
    '---', 'id: blank-type', 'type:', 'status: active',
    'created: 2026-05-30', 'updated: 2026-05-30', 'topics: [tests]',
    '---', '', '# blank-type', '',
  ].join('\n'));

  const report = [];
  checkSchema(iterActiveUnits(memories), memories, report);

  assert.ok(report.some(f => f.check === 'required-field-empty' && f.detail.includes("'type'")),
    'blank type must FAIL, not pass silently');
}));

test('MEM-014: an oversized unit WARNs unit-oversize (benign)', () => withStore((memories) => {
  writeFileSync(join(memories, 'big.md'), unit({ id: 'big', body: '# big\n\n' + 'x'.repeat(11_000) }));
  writeFileSync(join(memories, 'small.md'), unit({ id: 'small' }));

  const report = [];
  checkSchema(iterActiveUnits(memories), memories, report);

  assert.ok(report.some(f => f.check === 'unit-oversize' && f.unit_id === 'big'));
  assert.equal(report.some(f => f.check === 'unit-oversize' && f.unit_id === 'small'), false);
  assert.ok(BENIGN_WARN_CHECKS.has('unit-oversize'), 'advisory — never blocks retrieval or startup');
}));
