import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import {
  checkIntegrity, checkSchema, exitCode, iterActiveUnits, iterAllUnitFiles,
} from '../../plugins/core/skills/core/scripts/check-units.mjs';

function withStore(fn) {
  const root = mkdtempSync(join(tmpdir(), 'check-units-'));
  try {
    const memories = join(root, '_memories');
    mkdirSync(memories, { recursive: true });
    return fn(memories);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
}

function unit({
  id,
  body = '',
  type = 'decision',
  edges = '',
}) {
  return [
    '---',
    `id: ${id}`,
    `type: ${type}`,
    'status: active',
    'created: 2026-05-30',
    'updated: 2026-05-30',
    'topics:',
    '  - tests',
    edges,
    '---',
    '',
    body || `# ${id}`,
    '',
  ].filter(line => line !== '').join('\n');
}

test('iterActiveUnits: returns real units regardless of their prose content', () => withStore((memories) => {
  writeFileSync(join(memories, 'real-unit.md'), unit({
    id: 'real-unit',
    body: '# Real unit\n\nOrdinary prose body — nothing here exempts it from validation.',
  }));

  const units = iterActiveUnits(memories);

  assert.equal(units.length, 1);
  assert.equal(units[0].id, 'real-unit');
}));

test('iterAllUnitFiles: returns real unit files regardless of their prose content', () => withStore((memories) => {
  writeFileSync(join(memories, 'real-unit.md'), unit({
    id: 'real-unit',
    body: '# Real unit\n\nOrdinary prose body — nothing here exempts it from validation.',
  }));

  const stems = iterAllUnitFiles(memories).map(path => path.split('/').at(-1));

  assert.deepEqual(stems, ['real-unit.md']);
}));

test('iterActiveUnits and iterAllUnitFiles: skip underscore-prefixed generated artifacts', () => withStore((memories) => {
  // Generated render artifacts use the `_` prefix; the prefix skip exempts them.
  writeFileSync(join(memories, '_capability-drift-log.md'), [
    '# Capability Drift Log',
    '',
    '> Generated artifact (not a unit). Regenerated by analyze-capability-drift.mjs.',
    '',
  ].join('\n'));

  assert.deepEqual(iterActiveUnits(memories), []);
  assert.deepEqual(iterAllUnitFiles(memories), []);
}));

test('checkIntegrity: edge targets resolve for ordinary real units', () => withStore((memories) => {
  writeFileSync(join(memories, 'source.md'), unit({
    id: 'source',
    edges: [
      'edges:',
      '  - type: depends-on',
      '    target: target',
    ].join('\n'),
  }));
  writeFileSync(join(memories, 'target.md'), unit({
    id: 'target',
    body: '# Target\n\nAn ordinary real unit.',
  }));

  const report = [];
  checkIntegrity(iterActiveUnits(memories), memories, new Date(Date.UTC(2026, 4, 30)), report);

  assert.equal(report.some(r => r.check === 'dangling-edge'), false);
}));

// --- Track A: validator fixes (Codex co-existence workstream, 2026-06-01) ---

test('A1: flow-style YAML topics array does NOT trigger topics-format warning', () => withStore((memories) => {
  // Inline array form — valid YAML, was being parsed as a scalar string.
  writeFileSync(join(memories, 'flow.md'), [
    '---', 'id: flow', 'type: decision', 'status: active',
    'created: 2026-05-30', 'updated: 2026-05-30',
    'topics: [source-authority, launch-readiness, execution]',
    '---', '', '# flow', '',
  ].join('\n'));

  const report = [];
  checkSchema(iterActiveUnits(memories), memories, report);

  const topicsWarn = report.filter(f => f.check === 'topics-format');
  assert.equal(topicsWarn.length, 0, 'flow-style array must parse as a list');
}));

test('A2: references-topic edge to vocabulary is NOT a dangling-edge', () => withStore((memories) => {
  writeFileSync(join(memories, 'has-topic-edge.md'), unit({
    id: 'has-topic-edge',
    edges: 'edges:\n  - {type: references-topic, target: memory-boundary}\n  - {type: cites, target: real-target}',
  }));
  writeFileSync(join(memories, 'real-target.md'), unit({ id: 'real-target' }));

  const report = [];
  checkIntegrity(iterActiveUnits(memories), memories, new Date('2026-05-30'), report);

  const danglers = report.filter(f => f.check === 'dangling-edge');
  assert.ok(!danglers.some(f => f.detail.includes('memory-boundary')),
    'references-topic target is controlled vocab, not a unit — must not dangle');
}));

test('A3: exit-code tiers — benign warnings pass (0), degraded warn (1), fail (2)', () => {
  // Orphan/stale only → pass-with-warnings → 0 (must not block startup).
  assert.equal(exitCode([
    { level: 'WARN', check: 'orphan' },
    { level: 'WARN', check: 'stale' },
  ]), 0);
  // A non-benign warning is degraded → 1.
  assert.equal(exitCode([{ level: 'WARN', check: 'dangling-edge' }]), 1);
  // Any hard failure → 2.
  assert.equal(exitCode([
    { level: 'FAIL', check: 'required-field' },
    { level: 'WARN', check: 'orphan' },
  ]), 2);
  // Clean → 0.
  assert.equal(exitCode([]), 0);
});
