import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import {
  checkIntegrity, checkSchema, exitCode, iterActiveUnits, iterAllUnitFiles,
  isExternalRef, BENIGN_WARN_CHECKS, VALID_EDGE_TYPES, EDGE_TYPE_NORMALIZE,
} from '../../plugins/core/skills/core/scripts/check-units.mjs';

function withStore(fn) {
  const root = mkdtempSync(join(tmpdir(), 'check-units-'));
  try {
    const memories = join(root, '_memories');
    mkdirSync(memories, { recursive: true });
    return fn(memories);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
}

function unit({
  id,
  body = '',
  type = 'decision',
  edges = '',
}) {
  return [
    '---',
    `id: ${id}`,
    `type: ${type}`,
    'status: active',
    'created: 2026-05-30',
    'updated: 2026-05-30',
    'topics:',
    '  - tests',
    edges,
    '---',
    '',
    body || `# ${id}`,
    '',
  ].filter(line => line !== '').join('\n');
}

test('iterActiveUnits: returns real units regardless of their prose content', () => withStore((memories) => {
  writeFileSync(join(memories, 'real-unit.md'), unit({
    id: 'real-unit',
    body: '# Real unit\n\nOrdinary prose body — nothing here exempts it from validation.',
  }));

  const units = iterActiveUnits(memories);

  assert.equal(units.length, 1);
  assert.equal(units[0].id, 'real-unit');
}));

test('iterAllUnitFiles: returns real unit files regardless of their prose content', () => withStore((memories) => {
  writeFileSync(join(memories, 'real-unit.md'), unit({
    id: 'real-unit',
    body: '# Real unit\n\nOrdinary prose body — nothing here exempts it from validation.',
  }));

  const stems = iterAllUnitFiles(memories).map(path => path.split('/').at(-1));

  assert.deepEqual(stems, ['real-unit.md']);
}));

test('iterActiveUnits and iterAllUnitFiles: skip underscore-prefixed generated artifacts', () => withStore((memories) => {
  // Generated render artifacts use the `_` prefix; the prefix skip exempts them.
  writeFileSync(join(memories, '_capability-drift-log.md'), [
    '# Capability Drift Log',
    '',
    '> Generated artifact (not a unit). Regenerated by analyze-capability-drift.mjs.',
    '',
  ].join('\n'));

  assert.deepEqual(iterActiveUnits(memories), []);
  assert.deepEqual(iterAllUnitFiles(memories), []);
}));

test('checkIntegrity: edge targets resolve for ordinary real units', () => withStore((memories) => {
  writeFileSync(join(memories, 'source.md'), unit({
    id: 'source',
    edges: [
      'edges:',
      '  - type: depends-on',
      '    target: target',
    ].join('\n'),
  }));
  writeFileSync(join(memories, 'target.md'), unit({
    id: 'target',
    body: '# Target\n\nAn ordinary real unit.',
  }));

  const report = [];
  checkIntegrity(iterActiveUnits(memories), memories, new Date(Date.UTC(2026, 4, 30)), report);

  assert.equal(report.some(r => r.check === 'dangling-edge'), false);
}));

// --- Track A: validator fixes (Codex co-existence workstream, 2026-06-01) ---

test('A1: flow-style YAML topics array does NOT trigger topics-format warning', () => withStore((memories) => {
  // Inline array form — valid YAML, was being parsed as a scalar string.
  writeFileSync(join(memories, 'flow.md'), [
    '---', 'id: flow', 'type: decision', 'status: active',
    'created: 2026-05-30', 'updated: 2026-05-30',
    'topics: [source-authority, launch-readiness, execution]',
    '---', '', '# flow', '',
  ].join('\n'));

  const report = [];
  checkSchema(iterActiveUnits(memories), memories, report);

  const topicsWarn = report.filter(f => f.check === 'topics-format');
  assert.equal(topicsWarn.length, 0, 'flow-style array must parse as a list');
}));

test('A2: references-topic edge to vocabulary is NOT a dangling-edge', () => withStore((memories) => {
  writeFileSync(join(memories, 'has-topic-edge.md'), unit({
    id: 'has-topic-edge',
    edges: 'edges:\n  - {type: references-topic, target: memory-boundary}\n  - {type: cites, target: real-target}',
  }));
  writeFileSync(join(memories, 'real-target.md'), unit({ id: 'real-target' }));

  const report = [];
  checkIntegrity(iterActiveUnits(memories), memories, new Date('2026-05-30'), report);

  const danglers = report.filter(f => f.check === 'dangling-edge');
  assert.ok(!danglers.some(f => f.detail.includes('memory-boundary')),
    'references-topic target is controlled vocab, not a unit — must not dangle');
}));

// --- Cross-store / external-ref recognition (2026-06-03; obs-validator-cross-store-blindness) ---

test('cross-store prefixed edge target is external-ref, not dangling-edge', () => withStore((memories) => {
  writeFileSync(join(memories, 'src.md'), unit({
    id: 'src',
    edges: 'edges:\n  - {type: cites, target: feedback_no_naked_dc_references}',
  }));

  const report = [];
  checkIntegrity(iterActiveUnits(memories), memories, new Date('2026-06-03'), report);

  assert.equal(report.some(f => f.check === 'external-ref'), true,
    'feedback_-prefixed target lives in cross-project memory — recognized external, not a break');
  assert.equal(report.some(f => f.check === 'dangling-edge'), false);
}));

test('citation- and path-shaped edge targets are external-ref, not dangling-edge', () => withStore((memories) => {
  writeFileSync(join(memories, 'src.md'), unit({
    id: 'src',
    edges: [
      'edges:',
      '  - {type: cites, target: Park et al. 2023 (arxiv.org/abs/2304.03442)}',
      '  - {type: cites, target: docs/specs/2026-05-20-render-design.md}',
    ].join('\n'),
  }));

  const report = [];
  checkIntegrity(iterActiveUnits(memories), memories, new Date('2026-06-03'), report);

  assert.equal(report.filter(f => f.check === 'external-ref').length, 2,
    'a citation (whitespace/parens) and a file path (slash) are not unit ids');
  assert.equal(report.some(f => f.check === 'dangling-edge'), false);
}));

test('isExternalRef discriminates external refs from genuine unit ids', () => {
  assert.equal(isExternalRef('feedback_state_is_current_truth'), true);
  assert.equal(isExternalRef('project_bblens_tmobile_wrapper'), true);
  assert.equal(isExternalRef('reference_keel_handoff_channels'), true);
  assert.equal(isExternalRef('MemoryBank (arxiv.org/abs/2305.10250)'), true);
  assert.equal(isExternalRef('core-skill/skills/core/scripts/README.md'), true);
  // genuine unit-id shapes must NOT be masked — these still dangle if missing
  assert.equal(isExternalRef('dc-99-missing'), false);
  assert.equal(isExternalRef('obs-some-observation-2026-06-03'), false);
  assert.equal(isExternalRef('risk-12-mcp-write-arbitration'), false);
});

test('external-ref is a benign warn check (does not block exit code)', () => {
  assert.equal(BENIGN_WARN_CHECKS.has('external-ref'), true);
  assert.equal(exitCode([{ level: 'WARN', check: 'external-ref' }]), 0,
    'cross-store references must not degrade the exit code');
});

test('a genuinely missing unit-shaped target still flags dangling-edge (regression guard)', () => withStore((memories) => {
  writeFileSync(join(memories, 'src.md'), unit({
    id: 'src',
    edges: 'edges:\n  - {type: cites, target: dc-99-missing}',
  }));

  const report = [];
  checkIntegrity(iterActiveUnits(memories), memories, new Date('2026-06-03'), report);

  assert.equal(report.some(f => f.check === 'dangling-edge'), true,
    'a missing kebab-case unit id is a real break, not external');
}));

// --- Edge-type vocabulary: bless refines/amends, normalize relates (2026-06-03) ---

test('refines and amends are committed edge types (no edge-unknown-type)', () => withStore((memories) => {
  writeFileSync(join(memories, 'a.md'), unit({ id: 'a' }));
  writeFileSync(join(memories, 'b.md'), unit({ id: 'b' }));
  writeFileSync(join(memories, 'src.md'), unit({
    id: 'src',
    edges: 'edges:\n  - {type: refines, target: a}\n  - {type: amends, target: b}',
  }));

  const report = [];
  checkSchema(iterActiveUnits(memories), memories, report);

  assert.equal(report.some(f => f.check === 'edge-unknown-type'), false,
    'refines + amends are blessed — distinct from supersedes');
  assert.equal(VALID_EDGE_TYPES.has('refines'), true);
  assert.equal(VALID_EDGE_TYPES.has('amends'), true);
}));

test('relates flags edge-unknown-type and names its normalize target', () => withStore((memories) => {
  writeFileSync(join(memories, 'a.md'), unit({ id: 'a' }));
  writeFileSync(join(memories, 'src.md'), unit({
    id: 'src',
    edges: 'edges:\n  - {type: relates, target: a}',
  }));

  const report = [];
  checkSchema(iterActiveUnits(memories), memories, report);

  const warn = report.find(f => f.check === 'edge-unknown-type');
  assert.ok(warn, 'relates is not committed — must flag');
  assert.match(warn.detail, /normalize to 'cites'/, 'the safe-fix target is named for a mechanical relabel');
  assert.equal(EDGE_TYPE_NORMALIZE['relates'], 'cites');
}));

test('A3: exit-code tiers — benign warnings pass (0), degraded warn (1), fail (2)', () => {
  // Orphan/stale only → pass-with-warnings → 0 (must not block startup).
  assert.equal(exitCode([
    { level: 'WARN', check: 'orphan' },
    { level: 'WARN', check: 'stale' },
  ]), 0);
  // A non-benign warning is degraded → 1.
  assert.equal(exitCode([{ level: 'WARN', check: 'dangling-edge' }]), 1);
  // Any hard failure → 2.
  assert.equal(exitCode([
    { level: 'FAIL', check: 'required-field' },
    { level: 'WARN', check: 'orphan' },
  ]), 2);
  // Clean → 0.
  assert.equal(exitCode([]), 0);
});
